### ISSUE TITLE
Support multiple backends

### ISSUE THREAD

**Issue by oubiwann** [lfex/lhc#12]
* [x] Add support for [httpc](http://erlang.org/doc/man/httpc.html) (See issue #13)
* [x] Add support for [hackney](https://github.com/benoitc/hackney) (See issue #14)
* [x] Add support for [dlhttpc](https://github.com/ferd/dlhttpc) (See issue #15)
* [x] Add support for [ibrowse](https://github.com/cmullaparthi/ibrowse) (See issue #16)

Handle default backend and setting an explicit backend:
* [x] Select a default when running ``(lhc:start)`` (maybe use httpc as the default? and it folks want to use another backend, add it to their deps?) (See issue #19)
* [x] Added ``lhc:start/1`` which takes a backend (atom) as an argument starts lhc using that instead of the default (See issue #20)
* [x] Support configuring the default backend via an entry in ``lfe.config`` (See issue #21)

Backend-related tasks:
* [x] Add backend to user agent string (See issue #22)
* [x] Move existing lhttpc support to a backend (See issue #23)

**Comment by oubiwann** [comment]
Done.
